#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 05 00:38:33 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=photon_v1.2a.zip
enableShaders=true
