#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 03 21:48:49 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=photon_v1.2a.zip
enableShaders=true
